apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: logging
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  rbacRules:
    - apiGroups: [""]
      resources: ["nodes/proxy"]
      verbs: ["get"]

    
