apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: logging
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  rbacRules:
    - apiGroups: [""]
      resources: ["nodes/proxy"]
      verbs: ["get"]
  hostNetwork: true

---

apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
spec:
  service:
    logLevel: debug
    logFile: /var/log/fluent-operator/flb-debug.log
    parsersFile: parsers.conf