apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluentd
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  replicas: 3
  buffer:
    DisableBufferVolume: false
    pvc:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: fluentd-buffer-pvc
        namespace: logging
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: nfs-default
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem