apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingressroute
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`jenkins.jed.local`)
    services:
    - name: jenkins-service
      port: 8080
  tls:
    secretName: jenkins-ingress
