apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-local
  namespace: jenkins
spec:
  storageClassName: jenkins
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 7Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/jenkins_home

