apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment/deployment.yaml
configMapGenerator:
- name: traefik-config
  namespace: traefik
  files:
  - traefik-config.yaml