---
- name: Download the script repository
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Cleanup old directory
      ansible.builtin.file:
        path: /tmp/jed-cluster
        state: absent

    - name: Clone git repository
      ansible.builtin.git:
        repo: https://github.com/jjsiv/jed-cluster.git
        dest: /tmp/jed-cluster

- name: Configure crontab for each node
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Copy scripts
      ansible.builtin.copy:
        src: /tmp/jed-cluster/scripts/shell/
        dest: /etc/scripts/
        mode: 0755
    
    - name: Setup cronjob for system_stats.sh
      ansible.builtin.cron:
        name: System stats
        job: "/etc/scripts/cron/system_stats.sh > /dev/null"
        minute: "*/30"
        state: present
