apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus/deployment.yaml
- prometheus/ingressroute.yaml
- prometheus/rbac.yaml
- prometheus/service.yaml

namespace: monitoring

images:
- name: prom/prometheus
  newTag: v2.40.0


configMapGenerator:
- name: prometheus-config
  files:
  - prometheus/config/prometheus.rules
  - prometheus/config/prometheus.yml
  