apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealed-secrets/crds/crds.yaml
- sealed-secrets/clusterrolebindings.yaml
- sealed-secrets/clusterroles.yaml
- sealed-secrets/deployments.yaml
- sealed-secrets/rolebindings.yaml
- sealed-secrets/roles.yaml
- sealed-secrets/serviceaccounts.yaml
- sealed-secrets/services.yaml

images:
- name: docker.io/bitnami/sealed-secrets-controller
  newName: docker.io/bitnami/sealed-secrets-controller
  newTag: v0.19.3
