apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml

images:
- name: kubesphere/fluent-operator
  newTag: v1.7.0
  newName: kubesphere/fluent-operator
