apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: kubesphere/fluent-bit:v1.9.8
  fluentBitConfigName: fluent-bit-config
  args:
  - mkdir /var/log/fluent-operator
  volumesMounts:
  - mountPath: /var/log/fluent-operator
    name: fluent
  volumes:
  - hostPath:
      path: /var/log/fluent-operator
      type: ""
    name: fluent