apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-app
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: fluent
  source:
    path: gitops/fluent
    repoURL: https://github.com/jjsiv/jed-cluster
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
