apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: nfs-provisioner
  destination:
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  source:
    path: gitops/nfs-provisioner
    repoURL: https://github.com/jjsiv/jed-cluster.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
