apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: sealed-secrets
  source:
    path: gitops/sealed-secrets
    repoURL: https://github.com/jjsiv/jed-cluster
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
