apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: traefik-ingress
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: gitops/traefik/
    repoURL: https://github.com/jjsiv/jed-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
