apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sync
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: 'argoproj.io'
    kind: ''
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/argostuff.git
