apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  destinations:
  - namespace: jenkins
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/argostuff.git
