apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apps
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'rbac.authorization.k8s.io'
    kind: '*'
  destinations:
  - namespace: jenkins
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/argostuff.git
