apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: '*'
  - group: 'apps'
    kind: Deployment
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'rbac.authorization.k8s.io'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  destinations:
  - namespace: nginx-ingress
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/jed-cluster.git
