apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fluent-operator
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: 'fluentbit.fluent.io'
    kind: '*'
  - group: ''
    kind: ServiceAccount
  - group: 'apps'
    kind: Deployment
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'rbac.authorization.k8s.io'
    kind: '*'
  - group: ''
    kind: Namespace
  destinations:
  - namespace: logging
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/git-cluster.git
