apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fluent
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/jed-cluster.git
