apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jed
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  destinations:
  - namespace: jed
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/jed-cluster.git
