apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: 'rbac.authorization.k8s.io'
    kind: '*'
  - group: 'storage.k8s.io'
    kind: StorageClass
  destinations:
  - namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jjsiv/jed-cluster.git
