apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana/services.yaml
- grafana/statefulset.yaml
- grafana/secret-ingress.yaml
- grafana/grafana-ingressroute.yaml

namespace: grafana

images:
- name: grafana/grafana
  newTag: 9.1.0
